# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField()),
                ('bikeid', models.IntegerField()),
                ('from_station_id', models.IntegerField()),
                ('from_station_name', models.CharField(max_length=200)),
                ('to_station_id', models.IntegerField()),
                ('to_station_name', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
