# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='trip_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
